apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-ci-cd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-ci-cd-demo
  template:
    metadata:
      labels:
        app: eks-ci-cd-demo
    spec:
      containers:
      - name: eks-ci-cd-demo
        image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/eks-ci-cd-demo:latest

        ports:
        - containerPort: 3000
