name: CI/CD Pipeline

on:
push:
branches: [main]

jobs:
build:
runs-on: self-hosted

steps:
- name: Checkout source code
uses: actions/checkout@v4

- name: Verify Node.js installation
run: node -v

- name: Install dependencies
run: |
cd app
npm install

- name: Run application tests
run: |
cd app
npm test

- name: Debug token presence
run: echo "Token is set"
env:
SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

- name: SonarQube Scan
run: |
/opt/sonar-scanner/bin/sonar-scanner \
-Dsonar.projectKey=eks-ci-cd-demo \
-Dsonar.sources=./app \
-Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
-Dsonar.login=${{ secrets.SONAR_TOKEN }}

- name: Trivy Scan
run: trivy image ${{ secrets.ECR_REPOSITORY }}:latest || echo "Trivy scan skipped if image not present"

- name: Build Docker image
run: docker build -t ${{ secrets.ECR_REPOSITORY }}
